version: '3.8'

services:
  auth-db:
    image: postgres:15.2
    container_name: auth_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      auth-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APPLICATION_SECURITY_JWT_SECRET: ${JWT_SECRET}
      APPLICATION_SECURITY_JWT_EXPIRATION: ${JWT_EXPIRATION}
      APPLICATION_SECURITY_USERNAME: ${APP_USERNAME}
      APPLICATION_SECURITY_EMAIL: ${APP_EMAIL}
      APPLICATION_SECURITY_PASSWORD: ${APP_PASSWORD}
    volumes:
      - .m2:/root/.m2
      - ./logs:/app/logs

volumes:
  auth_postgres_data:
